#
# IMPORTANT NOTE
#
# This chart inherits from the bjw-s library chart. You can check the default values/options here:
# https://github.com/bjw-s/helm-charts/tree/main/charts/library/common
#
image:
  # -- image repository
  repository: ghcr.io/mealie-recipes/mealie
  # -- image tag
  # @default -- chart.appVersion
  tag:
  # -- image pull policy
  pullPolicy: IfNotPresent

strategy:
  type: Recreate

# -- environment variables.
# @default -- See below
env:
  TZ: UTC

# -- Configures service settings for the chart. Normally this does not need to be modified.
# @default -- See values.yaml
service:
  main:
    ports:
      http:
        port: 9000

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: false

# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
persistence:
  data:
    enabled: true
    mountPath: /app/data/
    accessMode: ReadWriteOnce
    size: 10Gi

# https://github.com/bitnami/charts/tree/master/bitnami/postgresql/#installing-the-chart
postgresql:
  enabled: false
#  auth:
#    postgresPassword: ""
#    username: ""
#    password: ""
#    database: ""
  persistence:
    enabled: true
    storageClass:
    accessModes:
      - ReadWriteOnce