apiVersion: v2
appVersion: v3.3.1
description: Mealie is a self hosted recipe manager and meal planner with a RestAPI backend and a reactive frontend application built in Vue for a pleasant user experience for the whole family.
name: mealie
version: 2.1.0
kubeVersion: ">=1.28.0-0"
keywords:
  - mealie
sources:
  - https://github.com/mealie-recipes/mealie
dependencies:
  - name: common
    version: 4.3.0
    repository: https://bjw-s-labs.github.io/helm-charts/
  - name: postgresql
    version: 17.0.0
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled