apiVersion: v2
appVersion: v1.10.2
description: Mealie is a self hosted recipe manager and meal planner with a RestAPI backend and a reactive frontend application built in Vue for a pleasant user experience for the whole family.
name: mealie
version: 1.0.1
kubeVersion: ">=1.16.0-0"
keywords:
  - mealie
sources:
  - https://github.com/mealie-recipes/mealie
dependencies:
  - name: common
    version: 1.5.1
    repository: https://bjw-s.github.io/helm-charts/
  - name: postgresql
    version: 12.6.0
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled